name: Feature
description: Suggest a change
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: body
    attributes:
      label: Description
    validations:
      required: true
